SRC       := vendor/phpdocumentor/phpdocumentor/src/phpDocumentor

OUTPUT    := example
CACHES    := $(OUTPUT)/.cache
MOUNT     := /data

TITLE     := 'テンプレート日本語化'

all: default-ja

default-ja:
	docker run --rm -v $(CURDIR):$(MOUNT) phpdoc/phpdoc:3 \
		-d $(SRC) \
		-t $(OUTPUT)/$@ \
		--cache-folder $(CACHES)/$@ \
		--template $(MOUNT)/$@ \
		--title $(TITLE) \
		--force

clean:
	-$(RM) -r $(OUTPUT)

.PHONY: all default-ja clean
